### ISSUE TITLE
No module named 'roi_align'

### ISSUE THREAD

**Issue by Joey-tao** [dxbdxx/BPFNet#1]
When I try "bash train.sh", it throw an error that is :
"
Traceback (most recent call last):
  File "train_align.py", line 6, in <module>
    from models.model import PalmAlignNet
  File "/home/qyt/BPFNet/BPFNet/models/model.py", line 12, in <module>
    from models.crop_and_resize import CropAndResize
  File "/home/qyt/BPFNet/BPFNet/models/crop_and_resize.py", line 7, in <module>
    import roi_align.crop_and_resize_cpu as crop_and_resize_cpu
ModuleNotFoundError: No module named 'roi_align'
"
And I am wondering how to fix this error?

**Comment by dxbdxx** [comment]
You need to compile the python module in models/RoIAlign following README in that directory.

**Comment by Joey-tao** [comment]
Thanks for your reply！ 
I tried to compile the module using "python setup.py install". 
But it throws an error as "gcc: error: roi_align/src/crop_and_resize.cpp: No such file or directory"
What should I do?

**Comment by dxbdxx** [comment]
Sorry for the missing files. I have updated src files.
