### ISSUE TITLE
ModuleNotFoundError: No module named 'roi_align.crop_and_resize_cpu'

### ISSUE THREAD

**Issue by ChNanAn** [dxbdxx/BPFNet#3]
there is always an error when importing the local module ,i indicated that roi_align was not found before ,
and then i marked it as the sources root ,but a new error  still appeared .

**Comment by dxbdxx** [comment]
You need to compile the python module in models/RoIAlign following README in that directory.

**Comment by czrb** [comment]
> 您需要按照该目录中的自述文件在 models/RoIAlign 中编译 python 模块。

您好，我在3090的服务器上，运行了setup.py，编译成功了，但是还是没有gpu文件诶，

**Comment by dxbdxx** [comment]
@czrb 我没明白你的问题，有没有报错信息？

**Comment by czrb** [comment]
ModuleNotFoundError：没有名为“roi_align.crop_and_resize_cpu
我也是这个错误。我看了ROIAlign的Readme，然后
python setup.py install
显示安装完成了，但是ROIAlign仍然没有，而且运行
python ./test这个文件也不行，还是报错，没有cpu或者GPU，这个是运行setup后会自动在roiAlign这个下生成的吗？
就是报错from roialign import roi_align.crop_and_resize_cpu，没有这个。
我是在3090的服务器上跑的，运行了这个命令
python train_align.py --name AIRS_rgb_ir --batch_size 64 --arc --s 32 --epochs 100 --save_freq 5

然后就报错没有“roi_align.crop_and_resize_cpu，我也安装了setup
谢谢您

**Comment by dxbdxx** [comment]
进入ROIAlign文件夹，python setup.py install 安装完成了肯定会有的，你按照ROIAlign文件夹下的README里给的python代码测试一下就行。

**Comment by ChNanAn** [comment]
我先运行了 python setup.py install 好像是没问题，然后运行 ./test.sh ,说
:[Errno 2] No such file or directory ': 
[Errno 2] No such file or directoryy ': 
[Errno 2] No such file or directoryd_resize_example.py
这是为什么

**Comment by ChNanAn** [comment]
我打开 test.sh文件，发现里面是这三个文件
python tests/test.py
python tests/test2.py
python tests/crop_and_resize_example.py
可是我在文件夹中没有发现有这三个文件啊

**Comment by dxbdxx** [comment]
@ChNanAn 用README中的python代码测试，sh中的测试文件我没有上传。
